# Generated by Django 5.0.6 on 2024-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cliente_groups_cliente_is_active_cliente_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=128),
        ),
    ]
