# Generated by Django 5.0.6 on 2024-06-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_cliente_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=50),
        ),
    ]
