# Generated by Django 5.0.6 on 2024-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_categoria_bateria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bateria',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
