# Generated by Django 5.0.6 on 2024-06-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bateria',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
